services:
    render:
        image: eltumero/graviola-render
        ports:
            - "4321:4321"
        depends_on:
            - event
    event:
        image: eltumero/graviola-event
        ports:
            - "8085:8085"
