export type TransactionStatus =
    | "NONE"
    | "PRE_AWAIT_CONFIRM"
    | "PRE_REJECTED"
    | "PRE_WAIT"
    | "PRE_READY"
    | "GEN_AWAIT_CONFIRM"
    | "GEN_REJECTED"
    | "GEN_WAIT"
    | "DONE"
    | "ERROR"
