import fs from 'fs'
import path from 'path'
import { Project, VariableDeclarationKind, Writers } from 'ts-morph'
import enumConverter from './enum'

const solidityFilePath = path.join(
    __dirname,
    '../src/Graviola/GraviolaMigrator.sol',
)

const outputFilePath = path.join(__dirname, './contracts.ts')

const solidityCode = fs.readFileSync(solidityFilePath, 'utf8')
const contractEnum = enumConverter(solidityCode)

if (!contractEnum) {
    process.exit(1)
}

const contractAddressEnumData = Object.fromEntries(
    Object.keys(contractEnum.enumData).map((key, index) => [
        key + '_ADDRESS',
        index,
    ]),
)

const project = new Project()
const sourceFile = project.createSourceFile(outputFilePath, '', {
    overwrite: true,
})

sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
        {
            name: contractEnum.enumName + 'Enum',
            initializer: Writers.assertion(
                Writers.object(contractEnum.enumData),
                'const',
            ),
        },
    ],
})

sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
        {
            name: contractEnum.enumName + 'AddressEnum',
            initializer: Writers.assertion(
                Writers.object(contractAddressEnumData),
                'const',
            ),
        },
    ],
})

sourceFile.addTypeAlias({
    name: 'DeployedContractAddressData',
    type: 'Record<keyof typeof DeployedContractAddressEnum, string>',
    isExported: true,
})

sourceFile.formatText()

fs.writeFileSync(
    outputFilePath,
    '// This file was autogenerated and should not be modified manually\n' +
        sourceFile.getText(),
)
console.log("Generated 'contracts.ts' file.")
