// This file was autogenerated and should not be modified manually
export const DeployedContractEnum = {
    VRF: 0,
    OAO: 1,
    COLLECTION: 2,
    KEYWORDS_VAULT: 3,
    GENERATOR: 4,
    COLLECTION_READ_PROXY: 5,
    MIGRATOR: 6,
    SCHEMA: 7
} as const;
export const DeployedContractAddressEnum = {
    VRF_ADDRESS: 0,
    OAO_ADDRESS: 1,
    COLLECTION_ADDRESS: 2,
    KEYWORDS_VAULT_ADDRESS: 3,
    GENERATOR_ADDRESS: 4,
    COLLECTION_READ_PROXY_ADDRESS: 5,
    MIGRATOR_ADDRESS: 6,
    SCHEMA_ADDRESS: 7
} as const;

export type DeployedContractAddressData = Record<keyof typeof DeployedContractAddressEnum, string>;
