[profile.default]
    src = "src"
    script = "script"
    test = "test"
    out = "out"
    solc = "0.8.25"
    evm_version = "cancun"

[rpc_endpoints]
    sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
    arb_sepolia = "https://arbitrum-sepolia.infura.io/v3/${API_KEY_INFURA}"