name: "Install and build the app"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Run Foundryup
        run: |
          foundryup

      - name: Install yarn
        run: npm i -g yarn

      - name: Generate types for website
        run: |
          cd contracts
          yarn
          yarn build
          yarn types

      - name: Run web
        run: |
          cd frontend
          yarn
          yarn build
