name: CI
on: push
jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9.13.2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build repo
              run: pnpm build
            - name: Clean repo
              run: pnpm run clean
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: .
                  if-no-files-found: error
                  retention-days: 5
    containerize:
        runs-on: ubuntu-22.04
        needs: build
        steps:
            - name: Download a Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-artifact
            - name: Build the Docker image (render)
              run: docker build . --file ./docker/render.Dockerfile --tag graviola/render:$(date +%s)
            - name: Build the Docker image (event)
              run: docker build . --file ./docker/event.Dockerfile --tag graviola/event:$(date +%s)
